---
name: Build release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed
          # files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: true # Validate all files everytime
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.10
        with:
          source: style.scss
          destination: style.css
          sourceComments: true

      - name: Create zip bundle
        run: |
          echo 'Zipping artifact'
          zip -r ./${{ github.sha }}.zip . -x ".*" "*.md" "super-linter.log" "*.scss"

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip

  publish:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v1.0.${{ github.run_number }}.${{ github.run_attempt }}
          release_name: Release
            v1.0.${{ github.run_number }}.${{ github.run_attempt }}
          body: New release triggered by commit ${{ github.sha }}
          draft: false
          prerelease: false
      #         body_path: CHANGELOG.md

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: zipped-bundle

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ github.sha }}.zip
          asset_name: pxssyinferno.zip
          asset_content_type: application/zip
