---
name: Build Pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label
    || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed
          # files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        continue-on-error: true
        env:
          # Validate all files everytime
          VALIDATE_ALL_CODEBASE: true
          # Function not found issues when running
          # PHPStan against a WordPress child theme
          VALIDATE_PHP_PHPSTAN: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.10
        with:
          source: style.scss
          destination: style.css
